 create table endereco (
        id bigint generated by default as identity,
        cep varchar(10) not null,
        numero_residencia varchar(10) not null,
        bairro varchar(100) not null,
        complemento varchar(100),
        cidade varchar(255) not null,
        logradouro varchar(255) not null,
        ponto_referencia varchar(255),
        primary key (id)
    );