create table ponto_moto (
        ativo boolean not null,
        contato_fk bigint unique,
        endereco_fk bigint unique,
        id bigint generated by default as identity,
        nome_ponto varchar(60) not null,
        primary key (id)
    );