create table funcionario (
        data_inscricao DATE,
        data_nascimento DATE,
        id bigint generated by default as identity,
        id_usuario bigint unique,
        matricula varchar(11) unique,
        cpf varchar(15) unique,
        tipo_sanguineo varchar(15) check (tipo_sanguineo in ('APOSITIVO','BPOSITIVO','ABPOSITIVO','OPOSITIVO','ANEGATIVO','BNEGATIVO','ABNEGATIVO','ONEGATIVO')),
        nome varchar(255) not null,
        primary key (id)
    );