
    create table auditoria_registros (
        data_criacao timestamp(6),
        data_evento timestamp(6) not null,
        data_modificacao timestamp(6),
        id bigint generated by default as identity,
        usuario_id bigint,
        numero_de_ordem varchar(10) not null,
        acao varchar(25) not null,
        descricao_acao varchar(25) not null,
        criado_por varchar(255),
        email_funcionario varchar(255) not null,
        modificado_por varchar(255),
        nome_condutor varchar(255) not null,
        nome_funcionario varchar(255) not null,
        primary key (id)
    );

    create table cliente (
        data_nascimento date not null,
        contato_fk bigint unique,
        endereco_fk bigint unique,
        id bigint generated by default as identity,
        id_usuario bigint not null unique,
        nome varchar(100) not null,
        primary key (id)
    );

    create table cnh (
        categoria varchar(2) not null check (categoria in ('A','AB','AC','AD','AE')),
        data_vencimento DATE not null,
        id bigint generated by default as identity,
        numero_habilitacao varchar(11) not null unique,
        primary key (id)
    );

    create table condutor (
        cadastro_ativo boolean not null,
        data_nascimento DATE not null,
        data_vencimento_alvara DATE,
        cnh_fk bigint unique,
        contato_fk bigint unique,
        data_criacao timestamp(6),
        data_modificacao timestamp(6),
        endereco_fk bigint unique,
        id bigint generated by default as identity,
        motocicleta_fk bigint unique,
        ponto_fk bigint,
        numero_ordem varchar(10) unique,
        tipo_sanguineo varchar(11),
        modalidade_condutor varchar(12) not null check (modalidade_condutor in ('MOTOTAXISTA','MOTOFRETISTA','AMBAS')),
        cpf varchar(15) not null unique,
        rg varchar(15) not null unique,
        apelido varchar(50),
        criado_por varchar(255),
        modificado_por varchar(255),
        nome varchar(255) not null,
        nome_mae varchar(255),
        nome_pai varchar(255),
        primary key (id)
    );

    create table contato (
        id bigint generated by default as identity,
        telefone_comercial varchar(15) unique,
        telefone_principal varchar(15) not null unique,
        primary key (id)
    );

    create table endereco (
        id bigint generated by default as identity,
        cep varchar(10) not null,
        numero_residencia varchar(10) not null,
        bairro varchar(100) not null,
        complemento varchar(100),
        cidade varchar(255) not null,
        logradouro varchar(255) not null,
        ponto_referencia varchar(255),
        primary key (id)
    );

    create table funcionario (
        data_inscricao DATE,
        data_nascimento DATE,
        id bigint generated by default as identity,
        id_usuario bigint unique,
        matricula varchar(11) unique,
        cpf varchar(15) unique,
        tipo_sanguineo varchar(15) check (tipo_sanguineo in ('APOSITIVO','BPOSITIVO','ABPOSITIVO','OPOSITIVO','ANEGATIVO','BNEGATIVO','ABNEGATIVO','ONEGATIVO')),
        nome varchar(255) not null,
        primary key (id)
    );

    create table mail (
        id bigint generated by default as identity,
        assunto varchar(255),
        conteudo TEXT,
        destinatario varchar(255),
        remetente varchar(255),
        primary key (id)
    );

    create table moto_marca (
        ativo boolean not null,
        id bigint generated by default as identity,
        nome_marca varchar(20) not null unique,
        descricao_marca varchar(255),
        primary key (id)
    );

    create table moto_modelo (
        ativo boolean not null,
        id bigint generated by default as identity,
        marca_fk bigint not null,
        modelo_moto varchar(60) not null unique,
        descricao_modelo varchar(255),
        primary key (id)
    );

    create table motocicleta (
        ano_fabricacao DATE not null,
        ano_modelo DATE not null,
        id bigint generated by default as identity,
        moto_modelo_fk bigint not null,
        tipo_placa varchar(8) check (tipo_placa in ('MERCOSUL','ANTIGA')),
        placa varchar(10) not null unique,
        situacao_moto varchar(13) check (situacao_moto in ('PROPRIA','LOCADA')),
        observacao varchar(500),
        primary key (id)
    );

    create table perfis (
        id bigint generated by default as identity,
        descricao varchar(255) not null unique,
        primary key (id)
    );

    create table ponto_moto (
        ativo boolean not null,
        contato_fk bigint unique,
        endereco_fk bigint unique,
        id bigint generated by default as identity,
        nome_ponto varchar(60) not null,
        primary key (id)
    );

    create table registro_cliente_contato (
        cliente_id bigint not null,
        data_contato timestamp(6) not null,
        id bigint generated by default as identity,
        numero_ordem varchar(10) not null,
        contato_condutor varchar(15) not null,
        email_cliente varchar(100) not null,
        marca_modelo_moto varchar(150) not null,
        nome_cliente varchar(150) not null,
        nome_condutor varchar(150) not null,
        primary key (id)
    );

    create table tokens (
        desativado boolean not null,
        data_expiracao timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        usuario_id bigint,
        token varchar(255) not null unique,
        primary key (id)
    );

    create table usuarios (
        ativo boolean not null,
        id bigint generated by default as identity,
        codigo_verificador varchar(100),
        email varchar(100) not null unique,
        senha varchar(255) not null,
        primary key (id)
    );

    create table usuarios_tem_perfis (
        perfil_id bigint not null,
        usuario_id bigint not null
    );

    create index idx_usuario_email 
       on usuarios (email);

    alter table if exists auditoria_registros 
       add constraint FK7v4lo4r6ck0elk4foxm7x3sn4 
       foreign key (usuario_id) 
       references usuarios;

    alter table if exists cliente 
       add constraint FKlaceuku4pj6vd3axsu6f7gupc 
       foreign key (contato_fk) 
       references contato;

    alter table if exists cliente 
       add constraint FKnfxnjh1vyf1shyc4jmg1cdj8l 
       foreign key (endereco_fk) 
       references endereco;

    alter table if exists cliente 
       add constraint FK8jxg42jrpamh07b7186gl6jpw 
       foreign key (id_usuario) 
       references usuarios;

    alter table if exists condutor 
       add constraint FKounksoij5brap569f51cd5wq9 
       foreign key (cnh_fk) 
       references cnh;

    alter table if exists condutor 
       add constraint FKghj1ge2ikrym6r5421d53ovy3 
       foreign key (contato_fk) 
       references contato;

    alter table if exists condutor 
       add constraint FKmjx54c6j20kh8wehdx66dnele 
       foreign key (endereco_fk) 
       references endereco;

    alter table if exists condutor 
       add constraint FKhffafuts6yt5vfwfrjbcw91np 
       foreign key (motocicleta_fk) 
       references motocicleta;

    alter table if exists condutor 
       add constraint FK1dmqnj9bpihxwf2s960oooytf 
       foreign key (ponto_fk) 
       references ponto_moto;

    alter table if exists funcionario 
       add constraint FKn7lf6rcoe0p0pc198hrtxqoe 
       foreign key (id_usuario) 
       references usuarios;

    alter table if exists moto_modelo 
       add constraint FKoughl0fqnrdqseil8lub141w2 
       foreign key (marca_fk) 
       references moto_marca;

    alter table if exists motocicleta 
       add constraint FK1q4uv7npjtpjc1h144dubqvab 
       foreign key (moto_modelo_fk) 
       references moto_modelo;

    alter table if exists ponto_moto 
       add constraint FK6ldyshafvcjgy0ypmlvje3ucb 
       foreign key (contato_fk) 
       references contato;

    alter table if exists ponto_moto 
       add constraint FK7nek2yrysw1mvciht4n00tobw 
       foreign key (endereco_fk) 
       references endereco;

    alter table if exists registro_cliente_contato 
       add constraint FKbkxcundusups43o7ris4hy6nn 
       foreign key (cliente_id) 
       references cliente;

    alter table if exists tokens 
       add constraint FK3lk2qjcmcoxjartjgb9mlc6kf 
       foreign key (usuario_id) 
       references usuarios;

    alter table if exists usuarios_tem_perfis 
       add constraint FKewye59sxbuklud72lsswd1mn1 
       foreign key (perfil_id) 
       references perfis;

    alter table if exists usuarios_tem_perfis 
       add constraint FKg6l7ittcd3wnixu65x04veyq6 
       foreign key (usuario_id) 
       references usuarios;
