create table mail (
        id bigint generated by default as identity,
        assunto varchar(255),
        conteudo TEXT,
        destinatario varchar(255),
        remetente varchar(255),
        primary key (id)
    );