create table registro_cliente_contato (
        cliente_id bigint not null,
        data_contato timestamp(6) not null,
        id bigint generated by default as identity,
        numero_ordem varchar(10) not null,
        contato_condutor varchar(15) not null,
        email_cliente varchar(100) not null,
        marca_modelo_moto varchar(150) not null,
        nome_cliente varchar(150) not null,
        nome_condutor varchar(150) not null,
        primary key (id)
    );