create table usuarios (
        ativo boolean not null,
        id bigint generated by default as identity,
        codigo_verificador varchar(100),
        email varchar(100) not null unique,
        senha varchar(255) not null,
        primary key (id)
    );

    create index idx_usuario_email 
       on usuarios (email);