create table cnh (
        categoria varchar(2) not null check (categoria in ('A','AB','AC','AD','AE')),
        data_vencimento DATE not null,
        id bigint generated by default as identity,
        numero_habilitacao varchar(11) not null unique,
        primary key (id)
    );