create table contato (
        id bigint generated by default as identity,
        telefone_comercial varchar(15) unique,
        telefone_principal varchar(15) not null unique,
        primary key (id)
    );