create table moto_marca (
        ativo boolean not null,
        id bigint generated by default as identity,
        nome_marca varchar(20) not null unique,
        descricao_marca varchar(255),
        primary key (id)
    );