create table moto_modelo (
        ativo boolean not null,
        id bigint generated by default as identity,
        marca_fk bigint not null,
        modelo_moto varchar(60) not null unique,
        descricao_modelo varchar(255),
        primary key (id)
    );