create table motocicleta (
        ano_fabricacao DATE not null,
        ano_modelo DATE not null,
        id bigint generated by default as identity,
        moto_modelo_fk bigint not null,
        tipo_placa varchar(8) check (tipo_placa in ('MERCOSUL','ANTIGA')),
        placa varchar(10) not null unique,
        situacao_moto varchar(13) check (situacao_moto in ('PROPRIA','LOCADA')),
        observacao varchar(500),
        primary key (id)
    );