create table auditoria_registros (
        data_criacao timestamp(6),
        data_evento timestamp(6) not null,
        data_modificacao timestamp(6),
        id bigint generated by default as identity,
        usuario_id bigint,
        numero_de_ordem varchar(10) not null,
        acao varchar(25) not null,
        descricao_acao varchar(25) not null,
        criado_por varchar(255),
        email_funcionario varchar(255) not null,
        modificado_por varchar(255),
        nome_condutor varchar(255) not null,
        nome_funcionario varchar(255) not null,
        primary key (id)
    );