create table tokens (
        desativado boolean not null,
        data_expiracao timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        usuario_id bigint,
        token varchar(255) not null unique,
        primary key (id)
    );