 create table cliente (
        data_nascimento date not null,
        contato_fk bigint unique,
        endereco_fk bigint unique,
        id bigint generated by default as identity,
        id_usuario bigint not null unique,
        nome varchar(100) not null,
        primary key (id)
    );